### ISSUE TITLE
Buttons in the Popup don't catch mouse events

### ISSUE THREAD

**Issue by ghost** [COMP523-VirtualMuseum/VirtualMuseum#8]
Sometimes when it looks like your mouse is over a button, Unity doesn't register the mouse being over it, so click handlers don't activate and it appears broken. Hover states aren't activated either. I made the hover states darker so that this issue is more apparent. It happens with the Increase Font Size, Decrease Font Size, and Close buttons. On some runs it happens and on other runs it doesn't.

**Comment by antonywang-eth** [comment]
I think this is caused by the code conflict with the Map Canvas. Will try to get a solution soon.
